version: '3.8'
services:
  dev_db:
    image: postgres
    ports: 
      - 5434:5432
    environment:
      POSTGRES_USER: innovate
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: todo
    networks:
      - innovate
networks:
  innovate:


  
